PCI-251 Add a new command for node_template to purge `abci_storage_rocksdb`.
adoriasoft/polkadot_cosmos_integration pull request #128
Opened 2021-02-18 16:40 UTC by maryjanyes

Add a new command for node_template `purge-abci-storage` to purge abci_storage_rocksdb directory;
Rename `on_new_session` method name to `call_on_new_session`.

2021-02-18 16:57 UTC, Mr-Leshiy requested changes

2021-02-18 16:57 UTC, Mr-Leshiy commented on src/command.rs
> +        Some(Subcommand::PurgeAbciStorage(ref cmd)) => {
We do not need to have to different cmd commands PurgeAbciStorage and PurgeChain. It should be only one cmd command PurgeChain which will remove all storages: original and our storage.

2021-02-18 16:57 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +    pub fn run(&self, config: &Configuration) -> sc_cli::Result<()> {
This function should processed the ```-y``` flag during the invoking it. Look at the PureChainCmd srtuct.

2021-02-18 17:17 UTC, Mr-Leshiy commented
Remove this function ```remove_abci_storage()``` from the command.rs

2021-02-19 09:14 UTC, Mr-Leshiy requested changes

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +pub struct PurgeChainWithStorageCmd {
add ```DataBaseParams``` as a field of this struct

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +impl CliConfiguration for PurgeChainWithStorageCmd {
add ```fn database_params(&self) -> Option<&DatabaseParams>``` method like in the PurgeChainCmd

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +            shared_params: sc_cli::SharedParams {
Copy ```shared_params```, do not construct it using constructor

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +            database_params: sc_cli::DatabaseParams {
same

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +        let database_params = self.database_params().unwrap_or(&sc_cli::DatabaseParams {
remove this

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +        let shared_params = self.shared_params();
remove this

2021-02-19 09:14 UTC, Mr-Leshiy commented on src/cli/commands.rs
> +            println!("Are you sure to remove {:?}? [y/N]: ", &db_path);
Ask that you want to remove all databases not only rocks db. If answer is 'yes' remove both database, the same with the non-interactive mode. 
As a result application should not ask user TWICE to reset the state.

2021-02-19 10:18 UTC, enfipy approved these changes

2021-02-19 19:41 UTC, Mr-Leshiy approved these changes

2021-02-20 11:51 UTC, merged