PCI-122-set-option-method
adoriasoft/polkadot_cosmos_integration pull request #59
Opened 2020-10-05 17:35 UTC by maryjanyes

2020-10-05 19:27 UTC, Mr-Leshiy requested changes
Напиши только плз тест на set_option и на info из предыдущей задачи, именно для их abci методов использую моки.

2020-10-06 13:32 UTC, enfipy commented on node/src/cosmos_rpc/mod.rs
> +        let query_params: types::ABCISetOption = _params.parse().unwrap();
Remove the underscore from `params`

2020-10-06 13:32 UTC, enfipy commented on node/src/cosmos_rpc/mod.rs
> +            .unwrap()
Try to get rid of all unwraps and replace them with `ok_or` or `map_err`

2020-10-06 13:32 UTC, enfipy commented on node/src/cosmos_rpc/types.rs
> +pub struct ABCISetOption {
Rename all `ABCI...` structs to `Abci...`

2020-10-06 16:45 UTC, closed without merging