PCI-209-modify-validators Complete update validators functionallity, alter tests.
adoriasoft/polkadot_cosmos_integration pull request #96
Opened 2020-12-16 19:56 UTC by maryjanyes

2020-12-17 09:40 UTC, Mr-Leshiy requested changes

2020-12-17 09:40 UTC, Mr-Leshiy commented on cosmos-abci/abci/src/grpc/protos.rs
> +    }
Add also setters for these fields

```Rust
fn set_events(&self, v : Vec<Event>) {
...
}

fn set_validator_updates(&self, v :Vec<ValidatorUpdate>) {
...
}
```

2020-12-17 09:40 UTC, Mr-Leshiy commented on cosmos-abci/src/lib.rs
> +        // todo
```suggestion
        // TODO : Save cosmos node validators into storage
```

2020-12-17 09:40 UTC, Mr-Leshiy commented on cosmos-abci/src/lib.rs
> +        // Save cosmos node validators into storage.
```suggestion
```

2020-12-17 09:40 UTC, Mr-Leshiy commented on cosmos-abci/src/lib.rs
> +                }
Print WARNING message if we can`t find substrate account for the corresponding cosmos account

2020-12-18 16:57 UTC, Mr-Leshiy approved these changes

2020-12-18 17:09 UTC, enfipy approved these changes

2020-12-19 12:02 UTC, merged